name: Semantic Release
on:
  push:
    branches:
      - master
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup asdf
        uses: asdf-vm/actions/install@v3

      - name: Compile frameworks
        working-directory: expo
        run: make build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          working_directory: ./expo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
